apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: reusable-components-library
  title: Reusable Components Library
  description: |
    Collection of standalone, reusable components.
    These components are independent from the main repository documentation.
spec:
  owner: platform-team
